server:
  port: 10010
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
spring:
  application:
    name: api-gateway
zuul:
  prefix: /api #添加路由前置
  routes:
    entrust-service: /entrust/**
    auth-service: /auth/**
    user-service: /user/**
    message-service: /message/**
    face-service: /face/**
  add-host-header: true #添加host头信息
  sensitive-headers:  #忽略敏感头信息
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #熔断超时时长：5000ms
ribbon:
  eureka:
    enable: true
  ConnectionTimeout: 2000 #ribbon连接超时时长
  ReadTimeout: 5000    #ribbon读取超时时长
  MaxAutoRetries: 0 #当前服务重试次数
  MaxAutoRetriesNextServer: 0 #切换服务重试次数
ce:
  jwt:
    pubKeyPath: f:/upload/id_rsa.pub # 公钥地址
    cookieName: CE-TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/user/faceVerify
      - /api/entrust
      - /api/face
