server:
  port: 10010
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
spring:
  application:
    name: api-gateway
zuul:
  prefix: /api #添加路由前置
  routes:
    entrust-service: /entrust/**
    user-service: /user/**
    auth-service: /auth/**
  add-host-header: true #添加host头信息
  sensitive-headers:  #忽略敏感头信息
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #熔断超时时长：5000ms